### ISSUE TITLE
Decide on tag to use for dev day

### ISSUE THREAD

**Issue by angela-li** [useR-stl/geospatial-dev-day#1]
At RStudio's [Tidyverse Dev Day](https://github.com/tidyverse/dev-day-2019), a tag of "tidy-dev-day" was used to indicate that an issue could be included in dev day, which allowed for contributors to do a [Github Search](https://github.com/search?q=is%3Aissue+label%3A%22tidy-dev-day+%3Anerd_face%3A) to find relevant issues (and indicate places where devs needed help)

A few potential tag ideas:

- "geo-dev-day"
- "r-spatial-dev-day"
- "r-spatial" + "help-wanted"

This was a good model to help individuals find issues to work on, but required some work on the part of package maintainers to identify and label discrete issues. 

(For larger problems of package design, etc, this may not be the best approach, and may require some thinking/discussion.)

Question for you: **What tag(s) make the most sense to use for this event?** Think about uniqueness, use beyond the day of the event, and burden on maintainers.

**Comment by tim-salabim** [comment]
I vote for either "geo-dev-day" or "rspatial-dev-day" (without `-`) as I think that "r-spatial-dev-day" (with `-`) may not be general enough and people might think it only refers to packages hosted at the r-spatial repo. On twitter we also usually use the #rspatial hashtag.

**Comment by angela-li** [comment]
Great, I wasn't sure what the convention should be, but that makes sense. I think "rspatial" is also easier to type than the extra dash in "r-spatial". 

Perhaps rspatial-dev-day is better than geo-dev-day in that it indicates R packages specifically?

**Comment by tim-salabim** [comment]
Agreed rspatial-dev-day is good, conveys R-spcificity and relates to (semi)popular Twitter hashtag

**Comment by angela-li** [comment]
Sounds good, I'll add the "rspatial-dev-day" tag to the README!
